/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorydatabase;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Acer
 */
public class MainPage extends javax.swing.JPanel {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SiderBar = new javax.swing.JPanel();
        BarMenu = new javax.swing.JLabel();
        BarSeparator = new javax.swing.JSeparator();
        Products_button = new javax.swing.JButton();
        Category_button = new javax.swing.JButton();
        Transaction_button = new javax.swing.JButton();
        Supplier_button = new javax.swing.JButton();
        User_button = new javax.swing.JButton();
        Logout_button = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Transactions = new javax.swing.JTable();
        MainPageLabel = new javax.swing.JLabel();

        setLayout(null);

        SiderBar.setBackground(new java.awt.Color(255, 255, 255));
        SiderBar.setPreferredSize(new java.awt.Dimension(209, 800));

        BarMenu.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        BarMenu.setText("MENU BAR");

        BarSeparator.setForeground(new java.awt.Color(102, 102, 102));
        BarSeparator.setEnabled(false);

        Products_button.setText("Products");
        Products_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Products_buttonActionPerformed(evt);
            }
        });

        Category_button.setText("Categories");
        Category_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_buttonActionPerformed(evt);
            }
        });

        Transaction_button.setText("Transactions");

        Supplier_button.setText("Suppliers");
        Supplier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_buttonActionPerformed(evt);
            }
        });

        User_button.setText("Users");

        Logout_button.setText("Logout");
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SiderBarLayout = new javax.swing.GroupLayout(SiderBar);
        SiderBar.setLayout(SiderBarLayout);
        SiderBarLayout.setHorizontalGroup(
            SiderBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarSeparator)
            .addGroup(SiderBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SiderBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Products_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Category_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transaction_button, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(Supplier_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(User_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logout_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(SiderBarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(BarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SiderBarLayout.setVerticalGroup(
            SiderBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiderBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BarSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(Products_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Category_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Transaction_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Supplier_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(User_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(Logout_button)
                .addGap(86, 86, 86))
        );

        add(SiderBar);
        SiderBar.setBounds(0, 0, 209, 800);

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setPreferredSize(new java.awt.Dimension(1610, 500));

        Transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TransactionId", "UserId", "TransactionType", "Total Amount", "Payment Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Transactions);

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentLayout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(Content);
        Content.setBounds(250, 70, 1610, 500);

        MainPageLabel.setBackground(new java.awt.Color(0, 0, 0));
        MainPageLabel.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        MainPageLabel.setText("Main Page");
        add(MainPageLabel);
        MainPageLabel.setBounds(910, 30, 410, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void Products_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Products_buttonActionPerformed
        
    }//GEN-LAST:event_Products_buttonActionPerformed

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        System.out.println("Logging out....");
        logoutLogic();
        
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void Category_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_buttonActionPerformed
      showCategoryPage();
    }//GEN-LAST:event_Category_buttonActionPerformed

    private void Supplier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_buttonActionPerformed
        // TODO add your handling code here:
        
        showSuppliers();
    }//GEN-LAST:event_Supplier_buttonActionPerformed

    
    public void showCategoryPage(){
  
        Categories categories = new Categories();
        categories.setVisible(true);
    }
    
    public void showSuppliers(){
        Suppliers supplier = new Suppliers();
        supplier.setVisible(true);
    }
    
    
    public void logoutLogic(){
        
        JFrame loginPage = new JFrame("Inventory Management System");
        JFrame mainPage = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        mainPage.setVisible(false);
        mainPage.dispose();
        
        loginPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        loginPage.setSize(1900, 800);
        loginPage.setLocationRelativeTo(null); // Center the window
        loginPage.getContentPane().add(new LoginPage());
        loginPage.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarMenu;
    private javax.swing.JSeparator BarSeparator;
    private javax.swing.JButton Category_button;
    private javax.swing.JPanel Content;
    private javax.swing.JButton Logout_button;
    private javax.swing.JLabel MainPageLabel;
    private javax.swing.JButton Products_button;
    private javax.swing.JPanel SiderBar;
    private javax.swing.JButton Supplier_button;
    private javax.swing.JButton Transaction_button;
    private javax.swing.JTable Transactions;
    private javax.swing.JButton User_button;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
